/*
 * Woden
 * Specification for Woden REST API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Woden) {
      root.Woden = {};
    }
    root.Woden.CreateUser = factory(root.Woden.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The CreateUser model module.
   * @module model/CreateUser
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CreateUser</code>.
   * @alias module:model/CreateUser
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>CreateUser</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateUser} obj Optional instance to populate.
   * @return {module:model/CreateUser} The populated <code>CreateUser</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('login'))
        obj.login = ApiClient.convertToType(data['login'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
      if (data.hasOwnProperty('privateKey'))
        obj.privateKey = ApiClient.convertToType(data['privateKey'], 'String');
      if (data.hasOwnProperty('CSR'))
        obj.CSR = ApiClient.convertToType(data['CSR'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} login
   */
  exports.prototype.login = undefined;

  /**
   * @member {String} email
   */
  exports.prototype.email = undefined;

  /**
   * @member {String} password
   */
  exports.prototype.password = undefined;

  /**
   * @member {String} privateKey
   */
  exports.prototype.privateKey = undefined;

  /**
   * @member {String} CSR
   */
  exports.prototype.CSR = undefined;

  return exports;

}));
