/*
 * Woden
 * Specification for Woden REST API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Woden);
  }
}(this, function(expect, Woden) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Login', function() {
      beforeEach(function() {
        instance = new Woden.Login();
      });

      it('should create an instance of Login', function() {
        // TODO: update the code to test Login
        expect(instance).to.be.a(Woden.Login);
      });

      it('should have the property login (base name: "login")', function() {
        // TODO: update the code to test the property login
        expect(instance).to.have.property('login');
        // expect(instance.login).to.be(expectedValueLiteral);
      });

      it('should have the property password (base name: "password")', function() {
        // TODO: update the code to test the property password
        expect(instance).to.have.property('password');
        // expect(instance.password).to.be(expectedValueLiteral);
      });

      it('should have the property certificate (base name: "certificate")', function() {
        // TODO: update the code to test the property certificate
        expect(instance).to.have.property('certificate');
        // expect(instance.certificate).to.be(expectedValueLiteral);
      });

      it('should have the property privateKey (base name: "privateKey")', function() {
        // TODO: update the code to test the property privateKey
        expect(instance).to.have.property('privateKey');
        // expect(instance.privateKey).to.be(expectedValueLiteral);
      });

    });
  });

}));
