/*
 * Woden
 * Specification for Woden REST API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ChangePassword', 'model/ChangePermissions', 'model/CreateFolder', 'model/CreateUser', 'model/Login', 'model/RevokePermissions', 'model/Vote', 'model/Voting', 'api/FileSystemApi', 'api/PermissionsApi', 'api/UserApi', 'api/VotingApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/ChangePassword'), require('./model/ChangePermissions'), require('./model/CreateFolder'), require('./model/CreateUser'), require('./model/Login'), require('./model/RevokePermissions'), require('./model/Vote'), require('./model/Voting'), require('./api/FileSystemApi'), require('./api/PermissionsApi'), require('./api/UserApi'), require('./api/VotingApi'));
  }
}(function(ApiClient, ChangePassword, ChangePermissions, CreateFolder, CreateUser, Login, RevokePermissions, Vote, Voting, FileSystemApi, PermissionsApi, UserApi, VotingApi) {
  'use strict';

  /**
   * Specification_for_Woden_REST_API.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Woden = require('index'); // See note below*.
   * var xxxSvc = new Woden.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Woden.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Woden.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Woden.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The ChangePassword model constructor.
     * @property {module:model/ChangePassword}
     */
    ChangePassword: ChangePassword,
    /**
     * The ChangePermissions model constructor.
     * @property {module:model/ChangePermissions}
     */
    ChangePermissions: ChangePermissions,
    /**
     * The CreateFolder model constructor.
     * @property {module:model/CreateFolder}
     */
    CreateFolder: CreateFolder,
    /**
     * The CreateUser model constructor.
     * @property {module:model/CreateUser}
     */
    CreateUser: CreateUser,
    /**
     * The Login model constructor.
     * @property {module:model/Login}
     */
    Login: Login,
    /**
     * The RevokePermissions model constructor.
     * @property {module:model/RevokePermissions}
     */
    RevokePermissions: RevokePermissions,
    /**
     * The Vote model constructor.
     * @property {module:model/Vote}
     */
    Vote: Vote,
    /**
     * The Voting model constructor.
     * @property {module:model/Voting}
     */
    Voting: Voting,
    /**
     * The FileSystemApi service constructor.
     * @property {module:api/FileSystemApi}
     */
    FileSystemApi: FileSystemApi,
    /**
     * The PermissionsApi service constructor.
     * @property {module:api/PermissionsApi}
     */
    PermissionsApi: PermissionsApi,
    /**
     * The UserApi service constructor.
     * @property {module:api/UserApi}
     */
    UserApi: UserApi,
    /**
     * The VotingApi service constructor.
     * @property {module:api/VotingApi}
     */
    VotingApi: VotingApi
  };

  return exports;
}));
