/*
 * Woden
 * Specification for Woden REST API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Woden);
  }
}(this, function(expect, Woden) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Woden.FileSystemApi();
  });

  describe('(package)', function() {
    describe('FileSystemApi', function() {
      describe('createFolder', function() {
        it('should call createFolder successfully', function(done) {
          // TODO: uncomment, update parameter values for createFolder call
          /*
          var body = new Woden.CreateFolder();
          body.name = "";
          body.parentFolder = "";

          instance.createFolder(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('downloadFile', function() {
        it('should call downloadFile successfully', function(done) {
          // TODO: uncomment, update parameter values for downloadFile call and complete the assertions
          /*
          var hash = "hash_example";
          var cid = "cid_example";

          instance.downloadFile(hash, cid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(File);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getFolder', function() {
        it('should call getFolder successfully', function(done) {
          // TODO: uncomment, update parameter values for getFolder call
          /*
          var hash = "hash_example";

          instance.getFolder(hash, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('search', function() {
        it('should call search successfully', function(done) {
          // TODO: uncomment, update parameter values for search call
          /*
          var name = "name_example";

          instance.search(name, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tree', function() {
        it('should call tree successfully', function(done) {
          // TODO: uncomment tree call
          /*

          instance.tree(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateFile', function() {
        it('should call updateFile successfully', function(done) {
          // TODO: uncomment, update parameter values for updateFile call
          /*
          var hash = "hash_example";
          var file = "/path/to/file.txt";

          instance.updateFile(hash, file, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('uploadFile', function() {
        it('should call uploadFile successfully', function(done) {
          // TODO: uncomment, update parameter values for uploadFile call
          /*
          var name = "name_example";
          var parentFolder = "parentFolder_example";
          var file = "/path/to/file.txt";

          instance.uploadFile(name, parentFolder, file, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('versions', function() {
        it('should call versions successfully', function(done) {
          // TODO: uncomment, update parameter values for versions call
          /*
          var hash = "hash_example";

          instance.versions(hash, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
