/*
 * Woden
 * Specification for Woden REST API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Woden);
  }
}(this, function(expect, Woden) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Woden.PermissionsApi();
  });

  describe('(package)', function() {
    describe('PermissionsApi', function() {
      describe('changePermissions', function() {
        it('should call changePermissions successfully', function(done) {
          // TODO: uncomment, update parameter values for changePermissions call
          /*
          var body = new Woden.ChangePermissions();
          body.email = "";
          body.hash = "";
          body.permission = "owner";

          instance.changePermissions(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('revokePermissions', function() {
        it('should call revokePermissions successfully', function(done) {
          // TODO: uncomment, update parameter values for revokePermissions call
          /*
          var body = new Woden.RevokePermissions();
          body.email = "";
          body.hash = "";
          body.permission = "unwrite";

          instance.revokePermissions(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
