/*
 * Woden
 * Specification for Woden REST API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Woden);
  }
}(this, function(expect, Woden) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Woden.VotingApi();
  });

  describe('(package)', function() {
    describe('VotingApi', function() {
      describe('createVoting', function() {
        it('should call createVoting successfully', function(done) {
          // TODO: uncomment, update parameter values for createVoting call
          /*
          var body = new Woden.Voting();
          body.hash = "";
          body.cid = "";
          body.dueDate = "";
          body.variants = "";
          body.excludedUsers = "";
          body.description = "";

          instance.createVoting(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getVoting', function() {
        it('should call getVoting successfully', function(done) {
          // TODO: uncomment getVoting call
          /*

          instance.getVoting(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateVoting', function() {
        it('should call updateVoting successfully', function(done) {
          // TODO: uncomment, update parameter values for updateVoting call
          /*
          var body = new Woden.Vote();
          body.variant = "";

          instance.updateVoting(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
